# Generated by Django 6.1.1 on 2026-09-25 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=8, unique=True)),
                ('title', models.CharField(default='Midterm', max_length=120)),
                ('minutes', models.PositiveIntegerField(default=30)),
                ('questions', models.JSONField(blank=True, default=list)),
                ('mode', models.CharField(choices=[('monitoring', 'Monitoring'), ('permitted', 'Lookup permitted'), ('paused', 'Paused')], default='monitoring', max_length=12)),
                ('mode_reason', models.CharField(blank=True, max_length=200)),
                ('owner_key', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('mode', models.CharField(blank=True, default='', max_length=12)),
                ('mode_reason', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(default='ok', max_length=12)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('answers', models.JSONField(blank=True, default=list)),
                ('score', models.IntegerField(default=0)),
                ('events', models.JSONField(blank=True, default=list)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('flag_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quiz.examsession')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
